# Generated by Django 4.0.3 on 2022-12-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
