# Generated by Django 4.0.3 on 2023-01-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='currency',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='packages.category'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='details',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='packages',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagesimage',
            name='image',
            field=models.ImageField(upload_to='package'),
        ),
    ]
