# Generated by Django 4.0.3 on 2023-01-03 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_airticketclass_trainticketclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='currency',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('departure_station', models.CharField(max_length=200)),
                ('arrival_station', models.CharField(max_length=200)),
                ('departure_date', models.CharField(max_length=200)),
                ('arrival_date', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('ticket_class', models.ManyToManyField(to='packages.trainticketclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('departure_airport', models.CharField(max_length=200)),
                ('arrival_airport', models.CharField(max_length=200)),
                ('departure_date', models.CharField(max_length=200)),
                ('arrival_date', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('ticket_class', models.ManyToManyField(to='packages.airticketclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
