# Generated by Django 4.0.3 on 2023-01-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_airticket_slug_hotel_slug_trainticket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airticket',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
