# Generated by Django 4.0.3 on 2023-01-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_airticket_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='activites_inc',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='activites_not',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
