# Generated by Django 4.0.3 on 2023-01-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_packages_activites_inc_packages_activites_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
