# Generated by Django 4.0.3 on 2023-01-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_hotel_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='category',
        ),
    ]
