# Generated by Django 4.0.3 on 2023-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_remove_packages_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packages',
            name='ratings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
