# Generated by Django 4.0.3 on 2023-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_packages_price_alter_packages_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainticket',
            name='ticket_class',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='category',
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transport',
            name='ratings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='seating_capacity',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='AirTicket',
        ),
        migrations.DeleteModel(
            name='AirTicketClass',
        ),
        migrations.DeleteModel(
            name='TrainTicket',
        ),
        migrations.DeleteModel(
            name='TrainTicketClass',
        ),
    ]
