# Generated by Django 4.0.3 on 2023-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_remove_trainticket_ticket_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.CharField(default='6', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ratings',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
