# Generated by Django 4.1.5 on 2023-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_hotel_rooms_alter_hotel_price_alter_hotel_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
