# Generated by Django 4.1.5 on 2023-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_alter_packagesimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packagesimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
