# Generated by Django 4.1.5 on 2023-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_category_status_hotel_status_hotelimage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='packagesimage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='packagesimage',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transportcategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transportcategory',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transportimage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transportimage',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
