# Generated by Django 4.1.5 on 2023-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='country',
            field=models.CharField(default='Pakistan', max_length=200),
            preserve_default=False,
        ),
    ]
