# Generated by Django 4.1.5 on 2023-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_alter_packages_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='Pakistan', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='country',
            field=models.CharField(default='Pakistan', max_length=200),
            preserve_default=False,
        ),
    ]
