# Generated by Django 4.1.5 on 2023-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_city_profile_country_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='A/292 Malir Kalaboard A-Area , Karachi', max_length=200),
            preserve_default=False,
        ),
    ]
